/**
 * render_video — render a registered Remotion composition to MP4 and drop it on
 * the Desktop, mirroring how Content Writer drops blogs.
 *
 * Runs `npx remotion render <compositionId> out/<slug>.mp4` inside the external
 * workspace (~/dev/_video-studio), then copies the MP4 to
 * ~/Desktop/Videos/<date>-<slug>/<slug>.mp4 and writes a video.md summary.
 *
 * The `aspect` input (9:16 | 16:9 | 1:1) is resolved to pixel dimensions via the
 * ASPECTS map so the summary records exactly what the panel asked for. The
 * actual frame size comes from how the agent registered the <Composition> in
 * src/Root.tsx — the agent is instructed to use the same aspect's dimensions.
 *
 * Hard rule: refuses any output path inside an installed .app bundle.
 *
 * The first render lazily downloads a headless Chrome shell (~150 MB) into the
 * workspace. That is one-time, on the user's machine, and never bundled into the
 * signed app. See docs/VIDEO-STUDIO.md.
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  ASPECTS,
  AspectKey,
  DEFAULT_FPS,
  isAspectKey,
  isInsideAppBundle,
  resolveVideoWorkspace,
  runInWorkspace,
  slugify,
  tailLog,
  videoOutputDir,
  workspaceExists,
} from './video-shared';

export interface RenderVideoInput {
  /** Composition id as registered in src/Root.tsx. */
  compositionId: string;
  /** Optional JSON string of input props passed via --props. */
  propsJson?: string;
  /** Output slug — drives the Desktop folder + filename. */
  slug: string;
  /** Aspect ratio chosen in the panel. */
  aspect: AspectKey;
}

export interface RenderVideoResult {
  success: boolean;
  videoPath?: string;
  folderPath?: string;
  error?: string;
}

function validate(input: RenderVideoInput): string | null {
  if (!input || typeof input !== 'object') return 'input is required';
  if (typeof input.compositionId !== 'string' || !input.compositionId.trim())
    return 'compositionId is required';
  if (typeof input.slug !== 'string' || !input.slug.trim()) return 'slug is required';
  if (!isAspectKey(input.aspect)) return "aspect must be one of '9:16', '16:9', '1:1'";
  if (input.propsJson !== undefined) {
    if (typeof input.propsJson !== 'string') return 'propsJson must be a JSON string';
    try {
      JSON.parse(input.propsJson);
    } catch {
      return 'propsJson is not valid JSON';
    }
  }
  return null;
}

/** Single-quote-safe shell argument. */
function shq(s: string): string {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

function buildSummary(
  input: RenderVideoInput,
  spec: { w: number; h: number; label: string; platforms: string },
  videoPath: string,
): string {
  const lines: string[] = [];
  lines.push(`# Video — ${input.slug}`);
  lines.push('');
  lines.push(`**Composition:** ${input.compositionId}`);
  lines.push(`**Aspect:** ${input.aspect} — ${spec.label}`);
  lines.push(`**Dimensions:** ${spec.w}×${spec.h} @ ${DEFAULT_FPS}fps`);
  lines.push(`**File:** ${path.basename(videoPath)}`);
  lines.push('');
  lines.push('## How to post');
  lines.push('');
  if (input.aspect === '9:16') {
    lines.push('- **Instagram Reels / TikTok / YouTube Shorts** — upload directly; 9:16 is native.');
    lines.push('- Add a caption + 3–5 hashtags. Keep the hook in the first 2 seconds.');
  } else if (input.aspect === '16:9') {
    lines.push('- **YouTube** — upload as a standard landscape video.');
    lines.push('- **LinkedIn / Facebook** — landscape autoplays in-feed; lead with motion.');
  } else {
    lines.push('- **Instagram / Facebook feed** — 1:1 maximizes feed real estate.');
    lines.push('- Pair with a short caption; the first line is the hook.');
  }
  lines.push('');
  lines.push('_Generated by AI Chief of Staff — Video Studio._');
  lines.push('');
  return lines.join('\n');
}

export async function renderVideo(input: RenderVideoInput): Promise<RenderVideoResult> {
  const err = validate(input);
  if (err) return { success: false, error: err };

  const workspace = resolveVideoWorkspace();
  if (!workspaceExists(workspace)) {
    return {
      success: false,
      error:
        'Remotion workspace not ready. Call scaffold_video_project first to create ~/dev/_video-studio.',
    };
  }

  const aspect = input.aspect as AspectKey;
  const spec = ASPECTS[aspect];
  const slug = slugify(input.slug);

  // In-workspace render target (out/<slug>.mp4).
  const workspaceOut = path.join(workspace, 'out', `${slug}.mp4`);

  // Final Desktop destination. Hard rule: never inside an .app bundle.
  const folderPath = videoOutputDir(slug);
  const videoPath = path.join(folderPath, `${slug}.mp4`);
  if (isInsideAppBundle(videoPath) || isInsideAppBundle(workspaceOut)) {
    return { success: false, error: 'Refusing to write a video inside an .app bundle.' };
  }

  // Build the render command. `--props` takes a JSON string.
  const parts = [
    'npx',
    'remotion',
    'render',
    shq(input.compositionId),
    shq(path.join('out', `${slug}.mp4`)),
  ];
  if (input.propsJson) {
    parts.push(`--props=${shq(input.propsJson)}`);
  }
  const cmd = parts.join(' ');

  const result = await runInWorkspace(cmd, {
    cwd: workspace,
    // First render pulls a headless Chrome shell (~150 MB) + encodes — allow time.
    timeoutMs: 20 * 60 * 1000,
  });

  if (!result.ok || !fs.existsSync(workspaceOut)) {
    const log = tailLog(`${result.stdout}\n${result.stderr}`, 40);
    return {
      success: false,
      error:
        (result.timedOut
          ? 'Render timed out. '
          : 'Render failed. ') +
        `Check the composition id ("${input.compositionId}") is registered in src/Root.tsx.\n\n` +
        log,
    };
  }

  // Copy the MP4 to the dated Desktop folder + write the summary.
  try {
    fs.mkdirSync(folderPath, { recursive: true });
    fs.copyFileSync(workspaceOut, videoPath);
    fs.writeFileSync(path.join(folderPath, 'video.md'), buildSummary(input, spec, videoPath));
  } catch (e) {
    return { success: false, error: `Render succeeded but copy to Desktop failed: ${(e as Error).message}` };
  }

  return { success: true, videoPath, folderPath };
}

export function getRenderVideoToolDefinition() {
  return {
    name: 'render_video',
    description:
      "Render a registered Remotion composition to MP4 in the external workspace (~/dev/_video-studio), then copy it to ~/Desktop/Videos/<date>-<slug>/<slug>.mp4 with a video.md summary. Inputs: compositionId (must be registered in src/Root.tsx), optional propsJson (a JSON string passed via --props), slug, and aspect (one of '9:16','16:9','1:1'). Call scaffold_video_project first. The first render lazily downloads a headless Chrome shell (~150 MB) and can take several minutes. Refuses to write inside an .app bundle.",
    input_schema: {
      type: 'object' as const,
      properties: {
        compositionId: {
          type: 'string',
          description: 'Composition id exactly as registered in src/Root.tsx.',
        },
        propsJson: {
          type: 'string',
          description: 'Optional. A JSON string of input props passed to the composition via --props.',
        },
        slug: {
          type: 'string',
          description: 'Short kebab-case slug for the Desktop folder + filename.',
        },
        aspect: {
          type: 'string',
          enum: ['9:16', '16:9', '1:1'],
          description:
            "Aspect ratio chosen in the Video Studio panel. 9:16=1080x1920, 16:9=1920x1080, 1:1=1080x1080.",
        },
      },
      required: ['compositionId', 'slug', 'aspect'],
    },
  };
}

export async function handleRenderVideoTool(input: unknown): Promise<string> {
  const result = await renderVideo(input as RenderVideoInput);
  return JSON.stringify(result);
}
